name: Quick Test

on:
  push:
    branches: ["*"]

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Quick functionality test
        run: |
          echo "🚀 Quick test - verifying basic functionality..."

          # Test import
          ./dist/cli.js import test-scripts/test-data/simple-collection.json test-quick

          # Test export
          ./dist/cli.js export test-quick test-quick-export.json

          # Verify JSON is valid
          node -e "JSON.parse(require('fs').readFileSync('test-quick-export.json', 'utf8')); console.log('✅ Quick test passed!')"

          # Cleanup
          rm -rf test-quick test-quick-export.json
